Models/Category.cs
namespace TestWebApp.Models
{
    public class Category
    {
        public int Id { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace TestWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApp.Models
{
    public class Login
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApp.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Nazwa jest wymagana")]
        public string Name { get; set; }
        
        [Required]
        public string Description { get; set; }
        
        [Required]
        public string Category { get; set; }

        [Required]
        public string ImageUrl { get; set; }
       
    }
}

Models/Register.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApp.Models
{
    public class Register
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

    }
}

Models/UserModel.cs
using Microsoft.AspNetCore.Identity;

namespace TestWebApp.Models
{
    public class UserModel : IdentityUser
    {

    }
}

Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Models;

namespace TestWebApp.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        private readonly SignInManager<UserModel> _signInManager;

        string Error = "";

        public AccountController(UserManager<UserModel> userManager, SignInManager<UserModel> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login userLoginData)
        {
            if (!ModelState.IsValid)
            {
                return View(userLoginData);
            }


            var result = await _signInManager.PasswordSignInAsync(userLoginData.UserName, userLoginData.Password, false, false);

            if (result.Succeeded)
            {
                Error = " ";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Error = "Hasło lub nazwa użytkownika nieprawidłowa";
                ViewData["Error"] = Error;
                return View();
            }
           
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Register userRegisterData)
        {
            if(!ModelState.IsValid)
            {
                return View(userRegisterData);
            }
            
            await _userManager.CreateAsync(new UserModel
            {
                Email = userRegisterData.Email,
                UserName = userRegisterData.UserName

            }, userRegisterData.Password);


            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

      
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestWebApp.Models;

namespace TestWebApp.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [Route("polityka-prywatnosci")]
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Redirect()
        {
            return RedirectToAction("Index");
        }

        [Route("testowy-route/{name}")]
        public IActionResult Produkt(string name)
        {
            return View();
        }

    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Models;
using TestWebApp.Services.Interfaces;

namespace TestWebApp.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly IWarehouseService _warehouseService;

        public ProductController(IWarehouseService warehouseService)
        {
            _warehouseService = warehouseService;
        }


        public IActionResult Product()
        {
            var product = new Product
            {
                Id = 1,
                Category = "Samochod",
                Description = "To jest super samochod",
                Name = "BMW M5",
                ImageUrl = "https://ocdn.eu/pulscms-transforms/1/0bLk9kqTURBXy9iYTdiMWMxNDYzODVlMWUzYTNmZWEyMTQ0YTE5NDBiZC5qcGVnkpUDJAHNBwfNA_STBc0EsM0CpN4AAqEwAaExAA"
            };

            return View(product);

        }

        public IActionResult List()
        {
            var productList = _warehouseService.GetAll();
            return View(productList);
        }

        public IActionResult Data()
        {
            ViewBag.Name = "Jacek";

            return View();
        }

       
    }
}

Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Models;
using TestWebApp.Services;
using TestWebApp.Services.Interfaces;

namespace TestWebApp.Controllers
{
    [Authorize]

    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _warehouseService;

        public WarehouseController(IWarehouseService warehouseService)
        {
            _warehouseService = warehouseService;    
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Product body)
        {
            if (!ModelState.IsValid) return View(body);

            var id = _warehouseService.Save(body);

            TempData["ProductId"] = id;

            return RedirectToAction("List");
        }


        [HttpGet]
        public IActionResult List()
        {
            var products = _warehouseService.GetAll();
            return View(products);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var product = _warehouseService.Get(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _warehouseService.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Produkt.cshtml
@{
    ViewData["Title"] = "Produkt";
}

<h1>Produkt</h1>

Views/Product/Data.cshtml
@{
    ViewData["Title"] = "Data";
}

<h1>Data</h1>
<p>ViewBag: @ViewBag.Name</p>

Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<h1>Produkt Index</h1>

Views/Product/List.cshtml
@model IEnumerable<TestWebApp.Models.Product>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<ul>

    @foreach(var product in Model)
    {
        <li><img src="http://animal.discovery.com/mammals/cheetah/pictures/cheetah-picture.jpg" alt="Product image" /> @product.Category - @product.Name - @product.Id</li>
    }
</ul>

<h2>Warunek - tylko samochody</h2>

<ul>

    @foreach (var product in Model)
    {
        if (product.Category == "Samochod")
        {
            <li><img src="http://animal.discovery.com/mammals/cheetah/pictures/cheetah-picture.jpg" alt="Product image" /> @product.Category - @product.Name - @product.Id</li>
        }
    }
</ul>

Views/Product/Product.cshtml
@model TestWebApp.Models.Product

@{
    ViewData["Title"] = "Product";
}

<h1>Product</h1>
<p>@Model.Name</p>
<p>@Model.Description</p>
<p>@Model.Category</p>
<img src="https://ocdn.eu/pulscms-transforms/1/0bLk9kqTURBXy9iYTdiMWMxNDYzODVlMWUzYTNmZWEyMTQ0YTE5NDBiZC5qcGVnkpUDJAHNBwfNA_STBc0EsM0CpN4AAqEwAaExAA" alt="Zdjecie produktu" />

Views/Shared/_AddProductForm.cshtml
@model TestWebApp.Models.Product

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@using (Html.BeginForm("Add", "Warehouse", FormMethod.Post))
{
    @Html.ValidationSummary()

    <span>Nazwa produktu:</span> @Html.TextBoxFor(x => x.Name)
    ;
    <span>Opis produktu:</span> @Html.TextBoxFor(x => x.Description)
    ;
    <span>Kategoria produktu:</span> @Html.TextBoxFor(x => x.Category)
    ;
    <span>Url zdjecia produktu</span> @Html.TextBoxFor(x => x.ImageUrl);

    <button type="submit">Dodaj produkt</button>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sklep Internetowy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="List">Lista Produktów</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Add">Dodaj Produkt</a>
                        </li>

                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Wyloguj</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Logowanie</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Rejestracja</a>
                            </li>
                        }
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Warehouse/Add.cshtml
@model TestWebApp.Models.Product

@{
    ViewData["Title"] = "Add";
}

<h1>Formularz dodający produkt do magazynu</h1>

@Html.Partial("_AddProductForm", Model)

<p>ID po zapisie(TempData): <strong>@TempData["ProductId"]</strong></p>

Views/Warehouse/Details.cshtml
@model TestWebApp.Models.Product

<h1>Szczegoly produktu</h1>
<p>Opis: @Model.Description</p>
<p>Kategoria: @Model.Category</p>

Views/Warehouse/List.cshtml
@model IEnumerable<TestWebApp.Models.Product>
<link rel="stylesheet" type="text/css" href="ListStyle.css"/>
<h1>Lista produktow</h1>

<ol>
    @foreach(var product in Model)
    {
        <li>
            <img src="@product.ImageUrl" width="120" alt="Product image" /><br>
            <b>@product.Name</b> - @product.Category - <br>
            <a href="@Url.Action("Details","Warehouse", new{Id = product.Id})">Szczegoly</a><br>
            @using (Html.BeginForm("Delete", "Warehouse", FormMethod.Post))
            {
                <input type="hidden" name="Id" value="@product.Id"/>
                <button type="submit">Usuń</button>
            }
        </li>
    }
</ol>